# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GHNetwork-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GHNetwork-iOS
  pod 'GHNetwork',   :path => '../'
end
