# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
inhibit_all_warnings!

target 'GHNetwork-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  source 'https://github.com/CocoaPods/Specs.git'
  
  # Pods for GHNetwork-iOS
  pod 'GHNetwork',   :path => '../'
end
